CREATE TABLE NOTES
(
    ID          INT           NOT NULL AUTO_INCREMENT,
    COLUMN_NAME VARCHAR(100)  NOT NULL,
    CONTENTS    VARCHAR(1000) NOT NULL,
    CREATED_AT  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    WRITER      VARCHAR(32)   NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('해야할일', 'DAN 이 해야할 일 1', 'DAN');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('해야할일', 'DAN 이 해야할 일 2', 'DAN');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('해야할일', 'DAN 이 해야할 일 3', 'DAN');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('해야할일', '미슈가 해야할 일 4', '미슈');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('해야할일', '미슈가 해야할 일 5', '미슈');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('해야할일', '미슈가 해야할 일 6', '미슈');

INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('하는중', 'DAN 이 하는중 1', 'DAN');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('하는중', 'DAN 이 하는중 2', 'DAN');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('하는중', 'DAN 이 하는중 3', 'DAN');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('하는중', '미슈가 하는중 4', '미슈');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('하는중', '미슈가 하는중 5', '미슈');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('하는중', '미슈가 하는중 6', '미슈');

INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('다했어', 'SALLY 가 다했어 1', 'SALLY');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('다했어', 'SALLY 가 다했어 2', 'SALLY');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('다했어', 'SALLY 가 다했어 3', 'SALLY');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('다했어', 'JINIE 가 다했어 4', 'JINIE');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('다했어', 'JINIE 가 다했어 5', 'JINIE');
INSERT INTO NOTES(COLUMN_NAME, CONTENTS, WRITER)
VALUES ('다했어', 'JINIE 가 다했어 6', 'JINIE');

SELECT * FROM NOTES;

COMMIT;